// Player stats on a completely new profile
export const BASE_STATS = {
    health: 100,
    defense: 0,
    effective_health: 100,
    strength: 0,
    speed: 100,
    crit_chance: 30,
    crit_damage: 50,
    bonus_attack_speed: 0,
    intelligence: 0,
    sea_creature_chance: 20,
    magic_find: 0,
    pet_luck: 0,
    ferocity: 0,
    ability_damage: 0,
    mining_speed: 0,
    mining_fortune: 0,
    farming_fortune: 0,
    foraging_fortune: 0,
    pristine: 0,
    damage: 0,
    damage_increase: 0,
  };
  
  export const STAT_TEMPLATE = {
    health: 0,
    defense: 0,
    effective_health: 0,
    strength: 0,
    speed: 0,
    crit_chance: 0,
    crit_damage: 0,
    bonus_attack_speed: 0,
    intelligence: 0,
    sea_creature_chance: 0,
    magic_find: 0,
    pet_luck: 0,
    ferocity: 0,
    ability_damage: 0,
    mining_speed: 0,
    mining_fortune: 0,
    farming_fortune: 0,
    foraging_fortune: 0,
    pristine: 0,
    damage: 0,
    damage_increase: 0,
  };