/**
 * Ordered object of stats
 * @type {{[key:string]: {
 *   name: string
 *   nameLore: string // name found in items lore
 *   nameShort: string // up to 16 chars
 *   nameTiny: string // up to 6 chars
 *   symbol: string
 *   suffix: string
 *   color: string
 * }}}
 */

export const STATS_DATA = {
  health: {
    name: "Health",
    nameLore: "Health",
    nameShort: "Health",
    nameTiny: "HP",
    symbol: "❤",
    suffix: "",
    color: "c",
  },
  vitality: {
    name: "Vitality",
    nameLore: "Vitality",
    nameShort: "Vitality",
    nameTiny: "VT",
    symbol: "",
    suffix: "",
    color: "c",
  },
  health_regen: {
    name: "HealthRegen",
    nameLore: "Health Regen",
    nameShort: "HP Reg",
    nameTiny: "HPR",
    symbol: "",
    suffix: "",
    color: "c",
  },
  defense: {
    name: "Defense",
    nameLore: "Defense",
    nameShort: "Defense",
    nameTiny: "Def",
    symbol: "❈",
    suffix: "",
    color: "a",
  },
  strength: {
    name: "Strength",
    nameLore: "Strength",
    nameShort: "Strength",
    nameTiny: "Str",
    symbol: "❁",
    suffix: "",
    color: "c",
  },
  speed: {
    name: "Speed",
    nameLore: "Speed",
    nameShort: "Speed",
    nameTiny: "Spd",
    symbol: "✦",
    suffix: "",
    color: "f",
  },
  crit_chance: {
    name: "Crit Chance",
    nameLore: "Crit Chance",
    nameShort: "Crit Chance",
    nameTiny: "CC",
    symbol: "☣",
    suffix: "%",
    color: "9",
  },
  crit_damage: {
    name: "Crit Damage",
    nameLore: "Crit Damage",
    nameShort: "Crit Damage",
    nameTiny: "CD",
    symbol: "☠",
    suffix: "%",
    color: "9",
  },
  intelligence: {
    name: "Intelligence",
    nameLore: "Intelligence",
    nameShort: "Intelligence",
    nameTiny: "Int",
    symbol: "✎",
    suffix: "",
    color: "b",
  },
  bonus_attack_speed: {
    name: "Bonus Attack Speed",
    nameLore: "Bonus Attack Speed",
    nameShort: "Attack Speed",
    nameTiny: "Atk",
    symbol: "⚔",
    suffix: "%",
    color: "e",
  },
  sea_creature_chance: {
    name: "Sea Creature Chance",
    nameLore: "Sea Creature Chance",
    nameShort: "SC Chance",
    nameTiny: "SCC",
    symbol: "α",
    suffix: "%",
    color: "3",
  },
  magic_find: {
    name: "Magic Find",
    nameLore: "Magic Find",
    nameShort: "Magic Find",
    nameTiny: "MF",
    symbol: "✯",
    suffix: "",
    color: "b",
  },
  pet_luck: {
    name: "Pet Luck",
    nameLore: "Pet Luck",
    nameShort: "Pet Luck",
    nameTiny: "PL",
    symbol: "♣",
    suffix: "",
    color: "d",
  },
  true_defense: {
    name: "True Defense",
    nameLore: "True Defense",
    nameShort: "True Defense",
    nameTiny: "TD",
    symbol: "❂",
    suffix: "",
    color: "f",
  },
  ferocity: {
    name: "Ferocity",
    nameLore: "Ferocity",
    nameShort: "Ferocity",
    nameTiny: "Frc",
    symbol: "⫽",
    suffix: "",
    color: "c",
  },
  ability_damage: {
    name: "Ability Damage",
    nameLore: "Ability Damage",
    nameShort: "Ability Damage",
    nameTiny: "AD",
    symbol: "๑",
    suffix: "%",
    color: "c",
  },
  mining_speed: {
    name: "Mining Speed",
    nameLore: "Mining Speed",
    nameShort: "Mining Speed",
    nameTiny: "MngSpd",
    symbol: "⸕",
    suffix: "",
    color: "6",
  },
  mining_fortune: {
    name: "Mining Fortune",
    nameLore: "Mining Fortune",
    nameShort: "Mining Fortune",
    nameTiny: "MngFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  farming_fortune: {
    name: "Farming Fortune",
    nameLore: "Farming Fortune",
    nameShort: "Farming Fortune",
    nameTiny: "FrmFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  foraging_fortune: {
    name: "Foraging Fortune",
    nameLore: "Foraging Fortune",
    nameShort: "Foraging Fortune",
    nameTiny: "FrgFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  pristine: {
    name: "Pristine",
    nameLore: "Pristine",
    nameShort: "Pristine",
    nameTiny: "Prs",
    symbol: "✧",
    suffix: "",
    color: "5",
  },
  fishing_speed: {
    name: "Fishing Speed",
    nameLore: "Fishing Speed",
    nameShort: "Fishing Speed",
    nameTiny: "FS",
    symbol: "☂",
    suffix: "",
    color: "b",
  },
  bonus_pest_chance: {
    name: "Bonus Pest Chance",
    nameLore: "Bonus Pest Chance",
    nameShort: "Bonus Pest Chance",
    nameTiny: "BPC",
    symbol: "ൠ",
    color: "3",
  },
};

export const HIDDEN_STATS = [
  "Alchemy Wisdom",
  "Carpentry Wisdom",
  "Combat Wisdom",
  "Enchanting Wisdom",
  "Farming Wisdom",
  "Fishing Wisdom",
  "Foraging Wisdom",
  "Mining Wisdom",
  "Runecrafting Wisdom",
  "Social Wisdom",
];


const symbols = {
  powder: "᠅",
  soulflow: "⸎",
  dungeon_upgrade: "⚚",
  dye: "✿",
  health: "❤",
  defense: "❈",
  strength: "❁",
  speed: "✦",
  crit_chance: "☣",
  crit_damage: "☠",
  intelligence: "✎",
  bonus_attack_speed: "⚔",
  sea_creature_chance: "α",
  magic_find: "✯",
  pet_luck: "♣",
  true_defense: "❂",
  ferocity: "⫽",
  ability_damage: "๑",
  mining_speed: "⸕",
  mining_fortune: "☘",
  farming_fortune: "☘",
  foraging_fortune: "☘",
  pristine: "✧",
  fishing_speed: "☂",
  bonus_pest_chance: "ൠ",
  alchemy_wisdom: "᠅",
  carpentry_wisdom: "⸎",
  combat_wisdom: "⚚",
  enchanting_wisdom: "✿",
  farming_wisdom: "❀",
  fishing_wisdom: "☁",
  foraging_wisdom: "☘",
  mining_wisdom: "⚒",
  runecrafting_wisdom: "☾",
  social_wisdom: "☕",
};
export const SYMBOLS = symbols;

export const RARITIES = [
  "common",
  "uncommon",
  "rare",
  "epic",
  "legendary",
  "mythic",
  "divine",
  "supreme",
  "special",
  "very_special",
  "admin",
];
